### PR TITLE
some clean up to make it compile on my pc

### PR DESCRIPTION
**Pull request by eps696**

### CODE REVIEW

**Comment by elliotwoods** [comment]
ah interesting. so you actually do want the `packages` folder?
are you sure about that? the general rule is you don't want any binaries in a repo
and i'm pretty sure NuGet doesn't want you to travel the actual bins with the project
@azeno - sorry to ask. but is it right to `.gitignore` the `packages` folder or not?

**Comment by eps696** [comment]
i agree it's probably wrong idea to include binaries, the reason is simple - i didn't manage to make it properly restored and compiled without it. one of dlls i just copied from vvvv binaries (which is probably even worse).

it's my second attempt of compiling stuff and using git though, so not sure that can do more with it now )

---

eps

**Comment by eps696** [comment]
sorry for the mess - it does work without packages as well (if the whole
dir is removed)
not quite sure what was wrong with my prev attempts, anyway it's ok now

---

eps

**Comment by elliotwoods** [comment]
Let's get this one pulled in, and I can check up on my PC next time it comes up

**Comment by elliotwoods** [comment]
Thanks again for the PR!

**Pull request merged**
